export type NavItem = { title: string; path: string; description?: string; children?: NavItem[] };

export const navigation: NavItem[] = [
  { title: 'Individuals', path: '/individuals', children: [
    { title: 'Retirement', path: '/individuals/retirement', description: 'Plan an income that can last.' },
    { title: 'Investments', path: '/individuals/investments', description: 'Build wealth with considered choices.' },
    { title: 'Protection', path: '/individuals/protection', description: 'Protect what matters, thoughtfully.' },
    { title: 'Diaspora', path: '/individuals/diaspora', description: 'Invest at home, from wherever you are.' },
    { title: 'Financial wellbeing', path: '/individuals/financial-wellbeing', description: 'Build confidence around money.' },
  ]},
  { title: 'Organisations', path: '/organisations', children: [
    { title: 'Retirement & benefits', path: '/organisations/retirement-and-benefits', description: 'Better outcomes for your people.' },
    { title: 'Insurance', path: '/organisations/insurance', description: 'Resilience for complex organisations.' },
    { title: 'Trustee & governance', path: '/organisations/trustee-and-governance', description: 'Rigour, oversight and accountability.' },
    { title: 'Advisory & administration', path: '/organisations/advisory-and-administration', description: 'Expertise behind every decision.' },
    { title: 'Employee ownership', path: '/organisations/employee-ownership', description: 'Align people with long-term value.' },
    { title: 'Training', path: '/organisations/training', description: 'Sharper financial decision-making.' },
  ]},
  { title: 'Investments', path: '/investments', children: [
    { title: 'Funds', path: '/investments/funds', description: 'Explore our investment range.', children: [
      { title: 'Money Market', path: '/investments/funds/money-market' },
      { title: 'Dollar Money Market', path: '/investments/funds/dollar-money-market' },
      { title: 'Fixed Income', path: '/investments/funds/fixed-income' },
      { title: 'Balanced', path: '/investments/funds/balanced' },
      { title: 'Equity', path: '/investments/funds/equity' },
    ]},
    { title: 'Compare funds', path: '/investments/compare-funds', description: 'See options side by side.' },
    { title: 'Prices & documents', path: '/investments/fund-prices-and-documents', description: 'Current data and disclosures.' },
    { title: 'Impact Debt Fund', path: '/investments/impact-debt-fund', description: 'Capital directed towards measurable progress.' },
  ]},
  { title: 'Retirement', path: '/retirement', children: [
    { title: 'Personal Pension', path: '/retirement/personal-pension', description: 'A plan built around your future.' },
    { title: 'Employer Pension', path: '/retirement/employer-pension', description: 'A valuable benefit, well managed.' },
    { title: 'Umbrella Fund', path: '/retirement/umbrella-fund', description: 'Scale without added complexity.' },
    { title: 'Income Drawdown', path: '/retirement/income-drawdown', description: 'Flexible income after retirement.' },
    { title: 'NSSF Tier II', path: '/retirement/nssf-tier-ii', description: 'Compliant, capable administration.' },
  ]},
  { title: 'Insights', path: '/insights' },
  { title: 'About', path: '/about', children: [
    { title: 'Our story', path: '/about/our-story', description: 'The thinking that guides us.' },
    { title: 'Governance & leadership', path: '/about/governance-and-leadership', description: 'Accountability from the top.' },
    { title: 'Markets', path: '/about/markets', description: 'Where we serve clients.' },
    { title: 'Careers', path: '/about/careers', description: 'Do meaningful work with us.' },
    { title: 'Foundation', path: 'https://seed.seraphcyber.com/', description: 'Supporting lasting opportunity.' },
    { title: 'Regulatory information', path: '/about/regulatory-information', description: 'Our commitments and disclosures.' },
  ]},
  { title: 'Gallery', path: '/gallery' },
  { title: 'Foundation', path: 'https://seed.seraphcyber.com/' },
];

export const funds = [
  { name: 'Money Market', slug: 'money-market', type: 'Interest income', currency: 'KES', risk: 'Low', horizon: 'Minimum 1 month', tone: 'lime', minimum: 'KES 100', fee: '2% p.a.', liquidity: 'Typically T+2', objective: 'Generate interest income through interest-earning money market instruments with a maximum weighted average of 12 months.', invests: 'Fixed deposits, treasury bills, government securities, call deposits and commercial paper.', income: 'Interest is declared daily and credited monthly, net of charges.' },
  { name: 'Dollar Money Market', slug: 'dollar-money-market', type: 'USD capital preservation', currency: 'USD', risk: 'Low', horizon: 'Minimum 3 months', tone: 'mint', minimum: 'USD 500', fee: '2% p.a. + VAT', liquidity: 'Within 30 days', objective: 'Preserve US dollar capital while earning income through a diversified portfolio in Kenya and offshore.', invests: 'USD-denominated, high-quality short-term debt and money market securities.', income: 'Interest accrues daily and is credited monthly; distributions are reinvested.' },
  { name: 'Fixed Income', slug: 'fixed-income', type: 'Income & capital preservation', currency: 'KES', risk: 'Medium', horizon: 'Below 12 months', tone: 'lilac', minimum: 'KES 100', fee: '2% p.a.', liquidity: 'Typically T+4', objective: 'Preserve capital while generating regular interest income through diversified fixed-income securities.', invests: 'Bank deposits, treasury bills and bonds, corporate bonds and commercial paper, with a small permitted offshore allocation.', income: 'Interest income, with yield and capital gains as the primary drivers of return.' },
  { name: 'Balanced', slug: 'balanced', type: 'Income & diversified growth', currency: 'KES', risk: 'Medium', horizon: 'Minimum 1 year', tone: 'violet', minimum: 'KES 100', fee: '2% p.a.', liquidity: 'Moderate', objective: 'Seek long-term stability and capital growth with moderate investment risk and a reasonable level of current income.', invests: 'Fixed deposits, treasury bills and bonds, corporate bonds and listed or unlisted equities.', income: 'Interest income, dividends and capital growth.' },
  { name: 'Equity', slug: 'equity', type: 'Capital growth', currency: 'KES', risk: 'High', horizon: 'Minimum 3 years', tone: 'plum', minimum: 'KES 100', fee: '2% p.a.', liquidity: 'Lower', objective: 'Provide total return in the form of income and capital growth through participation in a diversified portfolio.', invests: 'Predominantly treasury bonds and equities or stocks.', income: 'Dividends, interest income and capital growth.' },
];

export type PageContent = {
  eyebrow: string; title: string; intro: string; highlights?: string[];
  sectionTitle?: string; sectionIntro?: string; features?: { title: string; text: string }[];
  steps?: { title: string; text: string }[]; faqs?: { q: string; a: string }[];
  notice?: string; cta?: string; video?: { src: string; eyebrow?: string; title?: string }; heroImage?: string;
};

export const pageContent: Record<string, PageContent> = {
  '/gallery': { eyebrow:'Enwealth gallery',title:'People. Purpose. Progress.',intro:'A visual record of Enwealth events, learning, community and work across the region.',highlights:['Events','Training','Community','Regional teams'],sectionTitle:'Stories in pictures.',notice:'[CONTENT REQUIRED] Approved gallery images, captions, dates and usage permissions are required before publication.',cta:'Contact Enwealth'},
  '/individuals': { eyebrow:'For families & individuals', title:'Plan today for the life you want tomorrow.', intro:'Investing, retirement, protection and financial education organised around your life stage—not around internal departments.', highlights:['Save & invest','Retirement planning','Insurance & protection','Financial education'], sectionTitle:'Four building blocks. One plan.', features:[
    {title:'Save & invest',text:'Five Enwealth Capital funds, from interest income to long-term growth.'},{title:'Retirement planning',text:'Personal Pension while you save, and Kesho Hela for regular income after retirement.'},{title:'Insurance & protection',text:'Motor, home, funeral and post-retirement medical cover.'},{title:'Financial education',text:'Research, market commentary and plain-language guidance.'}], steps:[{title:'Tell us where you are',text:'Start with income, dependants, existing cover and what you are working towards.'},{title:'See the gaps',text:'Map what you have against what your goals require.'},{title:'Agree a plan',text:'Set products, contribution levels and timelines.'},{title:'Track and adjust',text:'Review annually or whenever your circumstances change.'}], cta:'Request a conversation' },
  '/individuals/retirement': { eyebrow:'Retirement planning',title:'Protect and grow your future.',intro:'Retirement solutions for individuals, employers and people moving from saving into a regular retirement income.',heroImage:'/images/hero/portrait-of-happy-old-male-ethnic-elderly-african-768x432.jpg',highlights:['Personal Pension','Kesho Hela Income Drawdown','Diaspora & Expatriates Fund','Umbrella Fund'],sectionTitle:'A plan for every stage.',features:[{title:'While you save',text:'Build retirement savings through flexible contributions or an employer scheme.'},{title:'As you retire',text:'Draw a regular income while the remaining balance stays invested.'},{title:'Across borders',text:'Save through USD, GBP or KES investment accounts in the Diaspora Fund.'}],cta:'Explore retirement solutions'},
  '/individuals/investments': { eyebrow:'Enwealth Capital',title:'Funds built for your next chapter.',intro:'Participate in diversified portfolios designed around your investment horizon, income needs and appetite for risk.',heroImage:'/images/hero/savings-900x600.jpg',highlights:['Five sub-funds','Business-day dealing','Professionally managed','CMA-authorised scheme'],sectionTitle:'Choose with context.',features:[{title:'Income',text:'Money market and fixed-income options for interest income and capital preservation objectives.'},{title:'Balanced growth',text:'A mix of money market, debt and equity securities.'},{title:'Long-term growth',text:'Equity exposure for investors with a higher risk appetite and longer horizon.'}],notice:'Returns are not guaranteed. Unit prices may fall as well as rise.',cta:'Compare funds'},
  '/individuals/protection': { eyebrow:'Individual insurance',title:'Peace of mind for you and your loved ones.',intro:'Personal cover arranged by Enwealth Insurance Brokers across travel, health, personal accident, motor, home, funeral and post-retirement medical needs.',highlights:['Travel & health','Personal accident','Motor & home','Funeral & retirement medical'],sectionTitle:'Cover for real life.',features:[{title:'Travel, health & accident',text:'Cover for travel risks, medical expenses and accidental death, disablement or medical costs.'},{title:'Motor & domestic',text:'Protection for vehicles, residential buildings, household contents and selected personal items.'},{title:'Later-life protection',text:'Anaya supports access to healthcare in retirement; Faraja covers funeral expenses.'}],cta:'Talk to an insurance specialist'},
  '/individuals/diaspora': { eyebrow:'Diaspora & Expatriates Fund',title:'No matter where life takes you.',intro:'A retirement savings solution for Kenyans in the diaspora and expatriates working in Kenya or elsewhere in Africa.',highlights:['USD, GBP or KES accounts','KES 120,000 minimum per annum per fund','Low, medium or aggressive risk preference','Registered by the RBA and KRA'],sectionTitle:'Built across borders.',features:[{title:'Recognised in the UK',text:'A Qualified Recognised Overseas Pension Scheme recognised by HM Revenue & Customs.'},{title:'Choice of currency',text:'Invest through a USD, GBP or KES investment account.'},{title:'Your risk preference',text:'Members can indicate a low, medium or aggressive investment preference.'}],faqs:[{q:'Who is it for?',a:'Kenyans working in the diaspora, expatriates working in Kenya and expatriates working elsewhere in Africa.'},{q:'What is required to join?',a:'AML confirmation, a qualifying custodian bank account, source-of-funds declaration, selected fund and risk profile, an application and nominated beneficiaries.'}],cta:'Ask about the Diaspora Fund'},
  '/individuals/financial-wellbeing': { eyebrow:'Financial education',title:'Decisions are better when they are understood.',intro:'Research, member education and practical guidance across budgeting, saving, investing, debt management and retirement planning.',highlights:['Financial literacy','Member education','Pre-retirement training','Research'],sectionTitle:'Enwealth Conversations.',features:[{title:'Saving and investment behaviour',text:'Research into saving and investment behaviour across age groups in Kenya.'},{title:'Retiree financial wellbeing',text:'Research supporting retirees, near-retirees, schemes and policy bodies.'},{title:'Leaving a legacy',text:'Research exploring attitudes to inheritance in Kenya.'}],cta:'Explore insights'},
  '/organisations': { eyebrow:'For organisations',title:'Retirement, governance and protection—working together.',intro:'Administration, trustee services, consulting, insurance and training for employers, schemes, sponsors and members.',heroImage:'/images/hero/1-1.png',highlights:['Pension administration','Independent trusteeship','Insurance brokerage','Training & consulting'],sectionTitle:'A connected service ecosystem.',features:[{title:'Retirement & benefits',text:'Administration, umbrella arrangements and scheme support.'},{title:'Governance',text:'Independent trusteeship, principal officer and fiduciary services.'},{title:'People & risk',text:'Corporate insurance, employee ownership and education.'}],cta:'Talk to the team'},
  '/organisations/retirement-and-benefits': { eyebrow:'Pension administration',title:'Excellent administration is the bedrock of a well-run fund.',intro:'Licensed and regulated by the Retirement Benefits Authority in Kenya, with expertise across actuarial science, law, finance, economics and investments.',highlights:['Member records & benefits','Compliance management','Scheme accounting','Member and trustee training'],sectionTitle:'Our administration mandate.',features:[{title:'Core administration',text:'Member records, benefits processing, communication and income distribution.'},{title:'Compliance & secretarial',text:'Legal-document support, board meetings, minutes and action tracking.'},{title:'Accounting & education',text:'Books, reconciliations and training for members and trustees.'}],cta:'Discuss your scheme'},
  '/organisations/insurance': { eyebrow:'Corporate insurance',title:'Designed to keep your business running.',intro:'Cover for employees, members, property and operations—from group life and medical to specialist commercial risks.',highlights:['Group life & medical','WIBA & personal accident','Property & machinery','Marine, aviation & construction'],sectionTitle:'Protection across your organisation.',features:[{title:'People',text:'Group Life, Group Personal Accident, WIBA and Group Medical cover.'},{title:'Property & operations',text:'Fidelity, All Risks, Fire & Special Perils, Burglary and Machinery Breakdown.'},{title:'Specialist risks',text:'Marine, Hull & Cargo, Contractors All Risk and Aviation insurance.'}],cta:'Review your corporate cover'},
  '/organisations/trustee-and-governance': { eyebrow:'Independent trustee services',title:'Trusted governance and fiduciary oversight.',intro:'Independent trusteeship across retirement benefits, collective investments, private wealth, capital markets, employee benefit trusts and escrow arrangements.',highlights:['RBA licensed','CMA licensed','Independent by design','Kenyan-registered trustee entity'],sectionTitle:'Trust and fiduciary structures.',features:[{title:'Retirement & investments',text:'Trusteeship for retirement benefit funds and regulated collective investment schemes.'},{title:'Private wealth & succession',text:'Family trusts, SPVs, private trust companies and family investment companies.'},{title:'Capital markets',text:'Trustee and fiduciary services for notes, bonds, asset-backed securities and securitisations.'}],cta:'Discuss your structure'},
  '/organisations/advisory-and-administration': { eyebrow:'Consultancy services',title:'Here for you, every step of the way.',intro:'Consulting for trustees and sponsors of retirement benefits schemes, supported by administration, legal and accounting expertise.',highlights:['Strategy development','Conversions & mergers','Scheme liquidation','Policy & performance'],sectionTitle:'Practical support for scheme decisions.',features:[{title:'Strategy',text:'Fact-based plans that respond to current challenges and members’ long-term needs.'},{title:'Change',text:'Guidance through scheme conversions, mergers and winding-up processes.'},{title:'Governance',text:'Policy formulation and performance evaluation for trustees and service providers.'}],cta:'Request a consultation'},
  '/organisations/employee-ownership': { eyebrow:'ESOP administration',title:'Employee ownership, administered end to end.',intro:'Support through the full life cycle of an Employee Share Ownership Plan, from member records and scheme accounts to trusteeship and communication.',highlights:['Member administration','Scheme accounting','Trustee support','Employee communication'],sectionTitle:'What we administer.',features:[{title:'Member services',text:'Data, contributions, allocations, statements, benefits and member education.'},{title:'Scheme accounting',text:'Books, reconciliations, financial reporting, audit support and statutory returns.'},{title:'Trustee support',text:'Service-provider oversight, meetings, audits, advice and trade settlement liaison.'}],cta:'Talk about your ESOP'},
  '/organisations/training': { eyebrow:'Enwealth Training',title:'Bring out the best in everyone.',intro:'Training for trustees, members and organisations across retirement, financial literacy and periods of change.',heroImage:'/images/hero/enwtraining-7-scaled.jpg',highlights:['Trustee training','Pre-retirement training','Member education','Financial literacy'],sectionTitle:'Training that supports better decisions.',features:[{title:'Trustees & schemes',text:'Legal obligations, financial responsibilities, fiduciary duties and retirement benefits management.'},{title:'Members & retirees',text:'Pre-retirement preparation, member education and practical financial literacy.'},{title:'Organisational change',text:'Outplacement and change-management support during transitions.'}],cta:'Discuss a training programme'},
  '/investments': { eyebrow:'Enwealth Capital',title:'Undivided participation. Diversified opportunity.',intro:'The Enwealth Capital Unit Trust Scheme gives investors access to diversified portfolios of securities through five sub-funds.',heroImage:'/images/hero/3.png',highlights:['KES 100 minimum initial investment','USD 500 for Dollar Money Market','2% annual management fee','Dealing each Kenyan business day'],sectionTitle:'Five funds. Distinct roles.',features:[{title:'Money Market',text:'Interest income with low risk and high liquidity needs in mind.'},{title:'Fixed Income & Balanced',text:'Income and capital-growth objectives at a medium risk profile.'},{title:'Equity',text:'Long-term capital growth for investors with a higher risk appetite.'}],notice:'The scheme received CMA consent to register on 24 October 2022. Returns are not guaranteed.',cta:'Compare all funds'},
  '/investments/funds': { eyebrow:'Enwealth Capital Unit Trust Scheme',title:'Five funds. Distinct roles.',intro:'Choose from money market, dollar money market, fixed income, balanced and equity funds according to your objective, risk appetite and time horizon.',heroImage:'/images/hero/enwinsurance-5-600x403-1.jpg',highlights:['Low to high risk profiles','KES & USD options','Income & growth objectives','Business-day dealing'],sectionTitle:'Build around your objective.',features:[{title:'Preserve & earn',text:'Money market options focus on accessible interest income and capital-preservation objectives.'},{title:'Balance',text:'Fixed Income and Balanced funds combine income objectives with selective growth exposure.'},{title:'Grow',text:'The Equity Fund is designed for long-term total return and a higher risk appetite.'}],notice:'Returns are not guaranteed. Read the approved fund documents before investing.',cta:'Compare funds'},
  '/investments/impact-debt-fund': { eyebrow:'Alternative investments',title:'Deploying capital for a better tomorrow.',intro:'A Kenya-domiciled Alternative Investment Fund giving institutional investors access to structured private debt opportunities seeking stable, risk-adjusted returns and measurable development impact.',highlights:['Structured private debt','Regulated MFIs & select SMEs','Income and capital-preservation objectives','Measurable impact'],sectionTitle:'How capital creates impact.',features:[{title:'Deploy',text:'Capital is provided to regulated microfinance institutions and a select number of SMEs.'},{title:'Reach',text:'MFIs on-lend to qualifying SMEs and MSMEs.'},{title:'Measure',text:'Criteria include job creation, financial inclusion, women and youth empowerment, SME growth and sustainability.'}],notice:'For general information only. Investment is subject to offering documents, eligibility requirements, risk disclosures and regulatory approvals. Capital preservation is an objective, not a guarantee.',cta:'Contact the fund team'},
  '/retirement': { eyebrow:'Enwealth Pension',title:'Secure your future with us.',intro:'Financial security has two parts: protect what you have and grow what you will need.',heroImage:'/images/hero/2-1.png',highlights:['Personal Pension','Umbrella Fund','Kesho Hela Income Drawdown','Diaspora & Expatriates Fund'],sectionTitle:'From saving to drawing income.',features:[{title:'Save personally',text:'Flexible retirement saving for individuals, chamas, SACCOs and SMEs.'},{title:'Save through work',text:'An umbrella arrangement for employers and employees.'},{title:'Draw income',text:'A structured alternative to an annuity after retirement.'}],cta:'Find your retirement solution'},
  '/retirement/personal-pension': { eyebrow:'Personal Pension Scheme',title:'Flexible retirement saving, built around you.',intro:'For self-employed people, chamas, SACCOs and SMEs securing employees’ financial wellbeing in retirement.',highlights:['Minimum KES 1,000 contribution','No setup cost','Flexible contribution frequency','Approved for NSSF Tier II contributions'],sectionTitle:'Why save with the scheme?',features:[{title:'Tax treatment',text:'Kenyan contributions receive tax relief up to KES 240,000 per year; qualifying investment income is tax exempt.'},{title:'Independent governance',text:'Assets are held by a custodian and an independent corporate trustee oversees the scheme.'},{title:'Flexible access',text:'Pay by M-Pesa, cheque, salary stop order or standing order, monthly to annually.'}],faqs:[{q:'How do I join?',a:'Complete the application form and provide identification documents. A deed of adherence and membership certificate are then issued.'},{q:'Can I transfer an existing pension?',a:'Yes. Benefits from another scheme can be transferred at no cost.'}],cta:'Start your personal pension'},
  '/retirement/employer-pension': { eyebrow:'Employer retirement benefits',title:'A valuable benefit, professionally administered.',intro:'Administration, governance and member support for employers that want a well-run retirement benefit arrangement.',highlights:['Accurate member records','Benefits processing','Compliance support','Member education'],sectionTitle:'Support behind the scheme.',features:[{title:'Administration',text:'Records, benefit processing, communication and income distribution.'},{title:'Governance',text:'Board support, compliance management and legal opinions.'},{title:'Member experience',text:'Secure access to scheme information and education on rights and benefits.'}],cta:'Talk to our pensions team'},
  '/retirement/umbrella-fund': { eyebrow:'Umbrella pension solutions',title:'Scale without the setup burden.',intro:'An RBA-approved umbrella retirement benefits scheme for employers that want to join an established fund and receive NSSF Tier II contributions.',highlights:['No startup cost','Guaranteed or segregated option','KES 500,000 group life cover','Up to 60% of savings may secure a mortgage'],sectionTitle:'Shared scale. Individual member accounts.',features:[{title:'Economies of scale',text:'Shared arrangements reduce the impact of costs and support diversification.'},{title:'Investment choice',text:'Employers choose a segregated structure or a guaranteed option with capital protection and a minimum 4% return.'},{title:'Fully outsourced',text:'Trusteeship, investment, custody and administration are managed for the employer.'}],faqs:[{q:'Can an individual join?',a:'No. Members join through a participating employer.'},{q:'When are Tier II contributions due?',a:'By the 10th day of each month.'}],cta:'Discuss the Umbrella Fund'},
  '/retirement/income-drawdown': { eyebrow:'Kesho Hela',title:'Regular income. The balance stays invested.',intro:'A registered income drawdown arrangement for retired members seeking an alternative to a traditional annuity.',highlights:['Regular retirement income','Minimum 10-year drawdown','For members at retirement age','Registered with the RBA and KRA'],sectionTitle:'How Kesho Hela works.',features:[{title:'Draw',text:'Receive regular income based on a prescribed percentage of the running balance.'},{title:'Keep investing',text:'Investment income returns to the fund and forms part of the balance.'},{title:'Choose after 10 years',text:'Continue drawing, buy an annuity or take the balance as a lump sum.'}],faqs:[{q:'Who can join?',a:'Members who have reached retirement age.'},{q:'What happens on death?',a:'Funds may provide income to a nominated spouse or dependent children, or be paid to nominated beneficiaries or dependants.'}],cta:'Discuss income drawdown'},
  '/retirement/nssf-tier-ii': { eyebrow:'NSSF Tier II',title:'Effortless Tier II pension saving.',intro:'Use the Enwealth Umbrella Fund to opt out Tier II benefits into an approved retirement arrangement.',highlights:['Contributions due by the 10th','6% of qualifying salary band','KES 500,000 life cover','Member portal & financial literacy'],sectionTitle:'More than compliance.',features:[{title:'Protection',text:'Life cover for the principal member, plus last expense, permanent total disability and critical illness benefits.'},{title:'Future healthcare',text:'Members can make additional voluntary contributions towards post-retirement medical cover.'},{title:'Member support',text:'Online access, beneficiary updates, retirement tools and age-based financial education.'}],cta:'Talk to the Tier II team'},
  '/support': { eyebrow:'Customer support',title:'How can we help?',intro:'The support team is available Monday to Friday, 08:00–17:00 EAT.',highlights:['+254 20 278 8000','info@enwealth.co.ke','Enwealth Business Centre','Ngong Lane, Ngong Road, Nairobi'],sectionTitle:'Start with the right team.',features:[{title:'Scheme members',text:'Questions about benefits, contributions, access and personal details.'},{title:'Employers & trustees',text:'Scheme administration, governance, reporting and service support.'},{title:'Investors',text:'Fund applications, account access and product information.'}],cta:'Send an enquiry'},
  '/support/manage-account': { eyebrow:'Digital access',title:'Your accounts, in one place.',intro:'Use the Enwealth member portal for pension information or the investment portal for Enwealth Capital accounts.',highlights:['Pension member portal','Investment customer portal','Contribution history','Statements & beneficiary details'],sectionTitle:'Choose your account.',features:[{title:'Pension portal',text:'View contribution history, benefits information, statements and nominated beneficiaries.'},{title:'Investment portal',text:'Open and manage a Unit Trust account, submit requests and view current information.'}],cta:'Access your account'},
  '/support/contact': { eyebrow:'Contact Enwealth',title:'Talk to us.',intro:'Tell us what you need and the right team will come back to you.',highlights:['Monday–Friday, 08:00–17:00 EAT','+254 20 278 8000','info@enwealth.co.ke','Nairobi, Kenya'],sectionTitle:'Your enquiry, directed well.',features:[{title:'Scheme member',text:'For personal pension and retirement-benefit support.'},{title:'Employer',text:'For organisational retirement, insurance and training needs.'},{title:'Trustee',text:'For governance, administration and fiduciary support.'}],cta:'Send enquiry'},
  '/support/complaints': { eyebrow:'Complaints',title:'If something has gone wrong, tell us.',intro:'Raise a complaint through the support team and include your scheme or member number, what happened and the outcome you are seeking.',highlights:['Acknowledgement & reference','Investigation','A substantive response','Escalation options'],sectionTitle:'What happens next.',features:[{title:'1. Raise it',text:'Use the enquiry form or published contact details.'},{title:'2. We investigate',text:'You receive a reference and an answer, or an explanation if more time is needed.'},{title:'3. Escalate if needed',text:'Unresolved matters may be taken to the appropriate regulator.'}],notice:'[CONTENT REQUIRED] Compliance-approved acknowledgement and resolution timescales must be added before publication.',cta:'Raise a complaint'},
  '/support/faqs': { eyebrow:'Frequently asked questions',title:'Unit trusts, explained plainly.',intro:'Understand how pooled investments work, how to join and what risk means before you invest.',highlights:['Five sub-funds','Professional management','Diversification','Regulated environment'],sectionTitle:'Common questions.',faqs:[{q:'What is a Unit Trust?',a:'A fund that pools investors’ money into a diversified portfolio. Income can come from dividends, interest and capital gains.'},{q:'Are returns guaranteed?',a:'No. Returns vary with market conditions and the underlying portfolio.'},{q:'Can I redeem my investment?',a:'Yes. Submit a redemption request through the customer portal or Administrator; timing depends on the fund.'},{q:'How do I join?',a:'Create an account in the Enwealth Capital portal or submit an application with the required KYC documents.'}],cta:'Ask another question'},
  '/support/search': { eyebrow:'Search Enwealth',title:'Find the right information.',intro:'Search across investments, retirement, insurance, employer services, support and insights.',highlights:['Investments','Retirement','Insurance','Support'],sectionTitle:'Popular destinations.',features:[{title:'Fund information',text:'Compare objectives, risk profiles, fees, minimums and liquidity.'},{title:'Retirement support',text:'Explore personal pensions, employer arrangements and income drawdown.'},{title:'Contact the team',text:'Reach support Monday to Friday, 08:00–17:00 EAT.'}],cta:'Contact support'},
  '/about': { eyebrow:'About Enwealth',title:'A lifetime of financial wellbeing and dignity.',intro:'Enwealth Financial Services began in Kenya in 2011 and provides administration, trustee, consulting, insurance, investment and training services across African markets.',heroImage:'/images/hero/about.jpg',highlights:['Founded 8 February 2011','Rebranded as Enwealth in 2016','300+ corporate clients','Branches in Kenya, Uganda & Mauritius'],sectionTitle:'People. Purpose. Progress.',features:[{title:'Mission',text:'Driving sustainable economic value and transformation through innovation and technology.'},{title:'Philosophy',text:'An integrated ecosystem of shared economic value through innovation and fintech.'},{title:'Values',text:'Trust, vibrancy, care, excellence and innovation.'}],cta:'Discover our story'},
  '/about/our-story': { eyebrow:'Our story',title:'From pension administration to an integrated financial ecosystem.',intro:'Founded as Liberty Pension Services Limited in 2011, the business became Enwealth Financial Services in 2016 as it expanded ICT-led innovation and its regional reach.',video:{src:'/videos/4319342-hd_1920_1080_30fps.mp4',eyebrow:'Our story in motion',title:'From a Kenyan pension administrator to a regional financial group.'},highlights:['2011: founded in Kenya','2016: rebranded','10+ African markets reached','70+ technical staff'],sectionTitle:'Built around client experience.',features:[{title:'Expertise',text:'Teams across pension administration, consulting, legal, accounting, investments, insurance and training.'},{title:'Systems',text:'Robust platforms designed to protect data integrity, reporting and historical records.'},{title:'Relationships',text:'Dedicated relationship management and long-term partnership with clients and service providers.'}],cta:'Talk to Enwealth'},
  '/about/governance-and-leadership': { eyebrow:'Corporate governance',title:'Accountability from the top.',intro:'Enwealth publishes the board of Enwealth Financial Services Limited and leadership information on its corporate site.',highlights:['Board oversight','Cross-sector expertise','Client-centred culture','Regional leadership'],sectionTitle:'Leadership profiles.',notice:'Leadership names and biographies should be maintained from the approved corporate source and reviewed before publication.',features:[{title:'Board of directors',text:'The published board brings experience across law, banking, finance, governance, HR, entrepreneurship and investment.'},{title:'Executive leadership',text:'Operational leadership supports an integrated group spanning retirement, investment, insurance and training.'}],cta:'View approved leadership information'},
  '/about/markets': { eyebrow:'Regional reach',title:'Rooted in East Africa. Reaching further.',intro:'Branch offices in Kenya, Uganda and Mauritius, with operational reach in Rwanda, Zimbabwe, South Sudan, Tanzania, Zambia, Namibia, Ghana, Malawi and Botswana.',highlights:['Kenya','Uganda','Mauritius','10+ African markets reached'],sectionTitle:'Local grounding. Regional capability.',cta:'Contact a market team'},
  '/about/careers': { eyebrow:'Careers at Enwealth',title:'Be part of a purpose-driven team.',intro:'Grow, make an impact and help build a better tomorrow through work across financial services in Africa.',highlights:['Work that matters','Learning & development','Inclusive culture','Regional impact'],sectionTitle:'Start with real-world experience.',features:[{title:'Quarterly internships',text:'Undergraduate intakes run January–March, April–June, July–September and October–December.'},{title:'Application timing',text:'Applications open in the second month of the preceding quarter.'},{title:'Career growth',text:'Learn from practitioners across pensions, investment, insurance, governance and training.'}],cta:'View open positions'},
  '/about/foundation': { eyebrow:'Enwealth Foundation',title:'Investing in people today.',intro:'[CONTENT REQUIRED]',sectionTitle:'Foundation programmes.',notice:'The source site links to a separate Foundation website; approved programme content is required before this page is published.',cta:'Contact Enwealth'},
  '/about/regulatory-information': { eyebrow:'Regulatory information',title:'Who regulates Enwealth.',intro:'Licensing and investor warnings vary by service and market. Confirm all licence numbers with Compliance before publication.',highlights:['RBA & CMA — Kenya','IRA — Kenya','FSC — Mauritius','URBRA — Uganda'],sectionTitle:'Important investor information.',features:[{title:'Kenya',text:'Pension administration and consulting are regulated by the RBA; insurance brokerage by the IRA; the Unit Trust Scheme is offered with CMA permission.'},{title:'Mauritius',text:'Enwealth is licensed by the Financial Services Commission under licence PA19000013.'},{title:'Uganda',text:'Enwealth is licensed by the Uganda Retirement Benefits Regulatory Authority.'}],notice:'Past performance is not a guide to future performance. Unit prices may fall or rise, and capital and returns are not guaranteed. This is not investment advice.',cta:'Request a conversation'},
  '/legal': { eyebrow:'Legal',title:'Clear terms. Responsible use.',intro:'The legal library explains how Enwealth handles personal information, how the website may be used and which regulatory notices apply.',highlights:['Privacy policy','Terms of use','Regulatory information','Complaints'],sectionTitle:'Legal information.',features:[{title:'Privacy',text:'How Enwealth collects, uses, shares, protects and retains personal data.'},{title:'Website terms',text:'The rules governing informational, non-commercial use of this website and its content.'},{title:'Regulatory notices',text:'Market-specific licensing, investor warnings and escalation routes.'}],cta:'Contact Enwealth'},
  '/legal/privacy': { eyebrow:'Privacy policy',title:'How Enwealth handles personal data.',intro:'Enwealth collects, uses, discloses and protects personal data in line with the Kenya Data Protection Act 2019 and relevant laws in the markets where it operates.',highlights:['Lawful & transparent processing','Purpose limitation','Data minimisation','Secure retention'],sectionTitle:'Your information and your rights.',features:[{title:'What is collected',text:'Identification, contact, financial, transaction and website-usage information.'},{title:'Why it is used',text:'To provide services, execute transactions, meet legal duties, prevent fraud and improve customer support.'},{title:'Your rights',text:'Subject to legal exceptions, data subjects may seek access, correction, restriction, objection or deletion.'}],notice:'Personal data is generally retained for seven years where required by law, and longer where needed for complaints or anticipated litigation.',cta:'Ask a privacy question'},
  '/legal/terms': { eyebrow:'Terms of use',title:'Using this website.',intro:'By using the Enwealth website, visitors agree to its published terms. The content is general information and does not replace professional advice.',highlights:['Informational use','Protected intellectual property','No professional advice','Use at your own risk'],sectionTitle:'The essential terms.',features:[{title:'Use of content',text:'Content may be viewed, copied, printed and distributed for informational, non-commercial purposes with attribution, but not modified.'},{title:'Names and logos',text:'Enwealth names, logos and product marks may not be used without written permission.'},{title:'Limitations',text:'The website is provided as is; users should seek qualified advice before financial or business decisions.'}],notice:'Terms may be revised by publication on the website. Continued use after a revision constitutes agreement to the revised terms.',cta:'Contact Enwealth'},
};

export const articles = [
  { category: 'Insurance', title: 'The most important tech trends of insurance', date: '25 September 2023', time: 'Article' },
  { category: 'Retirement', title: 'Having fun cracking retirement', date: '25 September 2023', time: 'Article' },
  { category: 'Pensions', title: 'How much of your salary should you put towards pension vs savings?', date: '25 September 2023', time: 'Article' },
];
